import { SUCCESS } from '../Api/types'

export const FETCH_ENTITY = 'FETCH_ENTITY'
export const UPDATE_ENTITY = 'UPDATE_ENTITY'
export const CREATE_ENTITY = 'CREATE_ENTITY'
export const FETCH_ENTITIES = 'FETCH_ENTITIES'
export const DESTROY_ENTITY = 'DESTROY_ENTITY'

export const FETCH_ENTITY_SUCCESS = FETCH_ENTITY + SUCCESS
export const UPDATE_ENTITY_SUCCESS = UPDATE_ENTITY + SUCCESS
export const CREATE_ENTITY_SUCCESS = CREATE_ENTITY + SUCCESS
export const FETCH_ENTITIES_SUCCESS = FETCH_ENTITIES + SUCCESS
export const DESTROY_ENTITY_SUCCESS = DESTROY_ENTITY + SUCCESS

export const CLEAR_ENTITIES = 'CLEAR_ENTITIES'
